# Generated by Django 2.2.1 on 2019-05-13 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='blog',
            new_name='blog_info',
        ),
    ]
