# Generated by Django 2.2.1 on 2019-05-13 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190513_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='blog_info',
            new_name='blog',
        ),
    ]
