# Generated by Django 2.2.1 on 2019-05-13 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190513_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comments',
            new_name='title',
        ),
    ]
